version: '3.8'

services:
  wot-backend:
    container_name: wot-backend
    image: ghcr.io/kronnox/wot-backend:latest
    volumes:
      - .:/application
    ports:
      - "8000:8000"
    restart:
      on-failure
    networks:
      - shared
  quick-sketch:
    container_name: quick-sketch
    image: ghcr.io/kronnox/quick-sketch:latest
    depends_on:
      - wot-backend
    ports:
      - "80:80"
    restart:
      on-failure
    networks:
      - shared
networks:
  shared:
    driver: bridge
